name: Deploy AWS Resources

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create S3 Bucket
        run: |
          BUCKET_NAME="my-new-bucket-$(uuidgen | cut -c1-8)"
          if [ "${{ secrets.AWS_REGION }}" == "us-east-1" ]; then
          aws s3api create-bucket --bucket $BUCKET_NAME --region us-east-1
          else
          aws s3api create-bucket --bucket $BUCKET_NAME --region ${{ secrets.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}
          fi
          echo "Created S3 Bucket: $BUCKET_NAME"

      - name: Launch EC2 Instance
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0d682f26195e9ec0f \
            --instance-type t2.micro \
            --key-name Linux_KP \
            --security-group-ids sg-0271d7c61a0259293 \
            --query "Instances[0].InstanceId" --output text)
          echo "EC2 Instance launched: $INSTANCE_ID"
